#!/bin/sh

# Autostart Applications
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
feh --no-fehbg --bg-fill ~/Pictures/Dusk.jpg &
pgrep -x picom > /dev/null || picom --experimental-backends &
$HOME/.config/polybar/launch.sh

# Layout
bspc monitor -d I II III IV V VI VII VIII IX X

# Border Settings
bspc config border_width         2
bspc config window_gap           8
bspc config normal_border_color  "#21242B"
bspc config focused_border_color "#3F444A"

# Rules
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
